---

- name: platform dependent vars
  include_tasks: "{{ query('first_found', params, errors='ignore') }}"
  vars:
    params:
      - files:
          - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
          - "{{ ansible_distribution }}.yml"
          - "{{ ansible_os_family }}.yml"
          - "{{ ansible_system }}.yml"
        paths:
          - '{{ role_path }}/vars/'
        skip: true
  tags: [install, configure]

- name: platform dependent tasks
  include_tasks: "{{ query('first_found', params, errors='ignore') }}"
  vars:
    params:
      - files:
          - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
          - "{{ ansible_distribution }}.yml"
          - "{{ ansible_os_family }}.yml"
          - "{{ ansible_system }}.yml"
        paths:
          - '{{ role_path }}/tasks/platform/pre-install/'
        skip: true
  tags: install

- name: establish package
  package:
    name: elasticsearch
    state: present
  notify: setup tools
  tags: install

- name: setup data storage
  file:
    path: "{{ configuration['path']['data'] }}"
    owner: elasticsearch
    state: directory
  notify: restart elasticsearch
  tags: configure

- name: establish configuration
  template:
    src: "{{ item }}"
    dest: "{{ platform['elasticsearch']['configuration']['dir'] }}/{{ item | basename | regex_replace('\\.j2','') }}"
  notify: restart elasticsearch
  loop:
    - elasticsearch.yml.j2
    - jvm.options.j2
  tags: configure
