---

- name: establish dependencies
  package:
    name:
      - apt-transport-https
      - openjdk-*-jre-headless
    state: present
  tags: install

- name: establish elasticsearch repo key
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    id: D27D666CD88E42B4
    state: present
  tags: install

- name: establish elasticsearch repo
  lineinfile:
    line: "deb https://artifacts.elastic.co/packages/{{ version | int }}.x/apt stable main"
    path: /etc/apt/sources.list.d/elastic.list
    create: true
  register: apt_update
  tags: install

- name: udpate repositories
  when: apt_update.changed
  apt:
    update_cache: true
  tags: install
