---

- name: establish man directory
  when: ansible_connection == 'docker'
  file:
    path: /usr/share/man/man1
    state: directory

- name: enable universe repository
  when: ansible_distribution == "Ubuntu"
  apt_repository:
    repo: "{{ item }}"
    update_cache: true
  loop:
    - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
    - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates universe"
    - "deb http://security.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-security universe"

- name: establish dependencies
  apt:
    name: "{{ java_packages }}"
    state: present
  tags: install

- name: establish elasticsearch repo key
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    id: D27D666CD88E42B4
    state: present
  tags: install

- name: establish elasticsearch repo
  lineinfile:
    line: "deb https://artifacts.elastic.co/packages/{{ version | int }}.x/apt stable main"
    path: /etc/apt/sources.list.d/elastic.list
    create: true
  register: apt_update
  tags: install

- name: udpate repositories
  when: apt_update.changed
  apt:
    update_cache: true
  tags: install
